### ISSUE TITLE
Reset after power on

### ISSUE THREAD

**Issue by arurke** [TEConnectivity/MS8607_Arduino_Library#2]
Hi, maybe more a question than an issue:
The MS8607 datasheet states "The Reset sequence shall be sent once after power-on to make sure that the calibration PROM gets loaded into the internal register", however this is not done in your Arduino example. Can you explain the rationale behind it? Is the reset strictly necessary?

**Comment by williammarkezana** [comment]
Hi @arurke, this reset is actually recommended if the power supply is raising slowly. If your power supply raising slope is almost straight you should be fine without it. However I agree the source code should demonstrate the worst case scenario, I'll make sure it gets updated accordingly.

**Comment by arurke** [comment]
Thanks for clarifying
